-- ============================================================================
-- RLS Policies for Sahar Alsharq Admin Panel & Public Website
-- Enables public read/submission and restricts administrative actions to authenticated users.
-- ============================================================================

-- 1. Create inquiries table if it does not exist
CREATE TABLE IF NOT EXISTS public.inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text DEFAULT '',
  email text DEFAULT '',
  phone text DEFAULT '',
  message text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Enable RLS on all tables
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 2. Products policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.products;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.products;
CREATE POLICY "Enable read for everyone" ON public.products
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.products;
CREATE POLICY "Enable insert for authenticated users" ON public.products
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.products;
CREATE POLICY "Enable update for authenticated users" ON public.products
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.products;
CREATE POLICY "Enable delete for authenticated users" ON public.products
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 3. Categories policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.categories;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.categories;
CREATE POLICY "Enable read for everyone" ON public.categories
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.categories;
CREATE POLICY "Enable insert for authenticated users" ON public.categories
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.categories;
CREATE POLICY "Enable update for authenticated users" ON public.categories
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.categories;
CREATE POLICY "Enable delete for authenticated users" ON public.categories
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 4. Features policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.features;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.features;
CREATE POLICY "Enable read for everyone" ON public.features
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.features;
CREATE POLICY "Enable insert for authenticated users" ON public.features
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.features;
CREATE POLICY "Enable update for authenticated users" ON public.features
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.features;
CREATE POLICY "Enable delete for authenticated users" ON public.features
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 5. Branches policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.branches;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.branches;
CREATE POLICY "Enable read for everyone" ON public.branches
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.branches;
CREATE POLICY "Enable insert for authenticated users" ON public.branches
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.branches;
CREATE POLICY "Enable update for authenticated users" ON public.branches
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.branches;
CREATE POLICY "Enable delete for authenticated users" ON public.branches
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 6. Branch links policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.branch_links;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.branch_links;
CREATE POLICY "Enable read for everyone" ON public.branch_links
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.branch_links;
CREATE POLICY "Enable insert for authenticated users" ON public.branch_links
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.branch_links;
CREATE POLICY "Enable update for authenticated users" ON public.branch_links
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.branch_links;
CREATE POLICY "Enable delete for authenticated users" ON public.branch_links
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 7. Site settings policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable read for everyone" ON public.site_settings;
DROP POLICY IF EXISTS "Enable read for authenticated users" ON public.site_settings;
CREATE POLICY "Enable read for everyone" ON public.site_settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.site_settings;
CREATE POLICY "Enable insert for authenticated users" ON public.site_settings
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.site_settings;
CREATE POLICY "Enable update for authenticated users" ON public.site_settings
  FOR UPDATE USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.site_settings;
CREATE POLICY "Enable delete for authenticated users" ON public.site_settings
  FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================================
-- 8. Inquiries policies
-- ============================================================================
DROP POLICY IF EXISTS "Enable insert for public website" ON public.inquiries;
CREATE POLICY "Enable insert for public website" ON public.inquiries
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable select for authenticated users only" ON public.inquiries;
CREATE POLICY "Enable select for authenticated users only" ON public.inquiries
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON public.inquiries;
CREATE POLICY "Enable delete for authenticated users only" ON public.inquiries
  FOR DELETE USING (auth.role() = 'authenticated');
