-- ============================================================================
-- Database Schema & Seed Data: Al-Bayt Al-Khaliji
-- Project URL: https://vgddzokqdwfokpfbrrno.supabase.co
-- Run this in the Supabase SQL Editor to set up the database environment.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Create Tables
-- ----------------------------------------------------------------------------

-- A. Site Settings
CREATE TABLE IF NOT EXISTS public.site_settings (
  id text PRIMARY KEY,
  site_name text NOT NULL DEFAULT 'البيت الخليجي',
  site_description text DEFAULT '',
  contact_email text DEFAULT '',
  contact_phone text DEFAULT '',
  social_facebook text DEFAULT '',
  social_instagram text DEFAULT '',
  social_whatsapp text DEFAULT '',
  hero_image text DEFAULT '',
  products_per_page integer NOT NULL DEFAULT 12,
  hours_weekday text DEFAULT 'طوال أيام الأسبوع: 10:00 ص - 10:00 م',
  hours_friday text DEFAULT 'الجمعة: 2:00 م - 10:00 م',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- B. Features
CREATE TABLE IF NOT EXISTS public.features (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text DEFAULT '',
  icon text DEFAULT '',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- C. Branches
CREATE TABLE IF NOT EXISTS public.branches (
  id text PRIMARY KEY,
  name text NOT NULL,
  phone text DEFAULT '',
  phone_tel text DEFAULT '',
  mobile_1 text DEFAULT '',
  mobile_2 text DEFAULT '',
  landline text DEFAULT '',
  address_lines text[] NOT NULL DEFAULT ARRAY[]::text[],
  map_query text DEFAULT '',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- D. Branch Links
CREATE TABLE IF NOT EXISTS public.branch_links (
  id text PRIMARY KEY,
  branch_id text NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  type text NOT NULL,
  label text DEFAULT '',
  href text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- E. Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text DEFAULT '',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- F. Products
CREATE TABLE IF NOT EXISTS public.products (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text DEFAULT '',
  note text DEFAULT '',
  category_id text REFERENCES public.categories(id) ON DELETE SET NULL,
  images text[] NOT NULL DEFAULT ARRAY[]::text[],
  order_index integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- G. Inquiries
CREATE TABLE IF NOT EXISTS public.inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text DEFAULT '',
  email text DEFAULT '',
  phone text DEFAULT '',
  message text DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 2. Enable Row-Level Security (RLS)
-- ----------------------------------------------------------------------------

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 3. Configure RLS Policies
-- ----------------------------------------------------------------------------

-- A. Site Settings Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.site_settings;
CREATE POLICY "Enable read for everyone" ON public.site_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.site_settings;
CREATE POLICY "Enable all for authenticated users" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');

-- B. Features Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.features;
CREATE POLICY "Enable read for everyone" ON public.features FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.features;
CREATE POLICY "Enable all for authenticated users" ON public.features FOR ALL USING (auth.role() = 'authenticated');

-- C. Branches Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.branches;
CREATE POLICY "Enable read for everyone" ON public.branches FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.branches;
CREATE POLICY "Enable all for authenticated users" ON public.branches FOR ALL USING (auth.role() = 'authenticated');

-- D. Branch Links Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.branch_links;
CREATE POLICY "Enable read for everyone" ON public.branch_links FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.branch_links;
CREATE POLICY "Enable all for authenticated users" ON public.branch_links FOR ALL USING (auth.role() = 'authenticated');

-- E. Categories Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.categories;
CREATE POLICY "Enable read for everyone" ON public.categories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.categories;
CREATE POLICY "Enable all for authenticated users" ON public.categories FOR ALL USING (auth.role() = 'authenticated');

-- F. Products Policies
DROP POLICY IF EXISTS "Enable read for everyone" ON public.products;
CREATE POLICY "Enable read for everyone" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.products;
CREATE POLICY "Enable all for authenticated users" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- G. Inquiries Policies
DROP POLICY IF EXISTS "Enable insert for everyone" ON public.inquiries;
CREATE POLICY "Enable insert for everyone" ON public.inquiries FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.inquiries;
CREATE POLICY "Enable all for authenticated users" ON public.inquiries FOR ALL USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- 4. Initial Seed Data (Al-Bayt Al-Khaliji)
-- ----------------------------------------------------------------------------

-- A. Seed Site Settings
INSERT INTO public.site_settings (
  id, site_name, site_description, contact_email, contact_phone, 
  social_instagram, social_whatsapp, hours_weekday, hours_friday
) VALUES (
  'al-bayt-al-khaliji-settings',
  'البيت الخليجي',
  'عبايات وتصاميم خليجية فاخرة تناسب أناقتك اليومية ومناسباتك الخاصة بأعلى جودة وخامات راقية.',
  'info@albayt-khaliji.com',
  '+966500000000',
  'albayt_khaliji',
  '966500000000',
  'طوال أيام الأسبوع: 10:00 ص - 10:00 م',
  'الجمعة: 2:00 م - 10:00 م'
) ON CONFLICT (id) DO UPDATE SET
  site_name = EXCLUDED.site_name,
  site_description = EXCLUDED.site_description,
  contact_email = EXCLUDED.contact_email,
  social_instagram = EXCLUDED.social_instagram,
  social_whatsapp = EXCLUDED.social_whatsapp;

-- B. Seed Features
INSERT INTO public.features (id, title, description, icon, order_index) VALUES
('feat-1', 'خامات خليجية فاخرة', 'أقمشة كريب، إنترنت، وميني صالون مستوردة خصيصاً لأناقتك.', 'Gem', 1),
('feat-2', 'تطريز يدوي متقن', 'قصات خليجية كلاسيكية وعصرية منفذة بأيدي مصممين خبراء.', 'Scissors', 2),
('feat-3', 'توصيل سريع وآمن', 'نشحن طلباتك بعناية فائقة وتوصيل سريع لباب بيتك.', 'Truck', 3)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  order_index = EXCLUDED.order_index;

-- C. Seed Categories
INSERT INTO public.categories (id, title, description, order_index) VALUES
('gulf-abayas', 'عبايات خليجية', 'قصات خليجية كلاسيكية سوداء وراقية لأناقتك اليومية', 1),
('practical-abayas', 'عبايات عملية وخروج', 'تصاميم مريحة وخفيفة تناسب الدوام والخروج اليومي السريع', 2),
('occasions', 'عبايات مناسبات', 'عبايات مطرزة يدوياً بالخرز والشك الفاخر لمناسباتك السعيدة', 3)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  order_index = EXCLUDED.order_index;
